name: Build apk

on: [push, pull_request]

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Workaround for "Build-tool 33.0.0 is missing DX at ..." error
      run: |
                ln -s $ANDROID_SDK_ROOT/build-tools/33.0.0/d8 $ANDROID_SDK_ROOT/build-tools/33.0.0/dx
                ln -s $ANDROID_SDK_ROOT/build-tools/33.0.0/lib/d8.jar $ANDROID_SDK_ROOT/build-tools/33.0.0/lib/dx.jar

    - name: Add android sdk tools to path
      run: |
                export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools/
                export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
                export PATH=$PATH:$ANDROID_SDK_ROOT/emulator/

    - name: Install cordova
      run: sudo npm install -g cordova

    - name: Install yarn
      run: sudo npm install -g yarn

    - name: Setup project, install app plugins and deps
      run: yarn setup

    - name: Configure the platform
      run: yarn clean

    - name: Build Android prod aab
      run: yarn build android paid prod

    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: ./platforms/android/app/build/outputs/apk/release/*.apk
        if-no-files-found: error

